Repository open-feature/community, pull requests merged in 2022-05, with the labels that each got.

#62 Add governing board and TSC members
  governance-charter.md
Labels: governance

#68 Adding DomFleischmann to interested parties
  interested-parties.md
Labels: membership

#76 Add links to social media on the page
  README.md
Labels: community
